#!/usr/bin/env python3
"""
Cholot Replicator V2 - Fixed XML generation with proper formatting
"""

import json
import yaml
import xml.etree.ElementTree as ET
from datetime import datetime
from typing import Dict, Any, List
import re

class CholtReplicatorV2:
    def __init__(self):
        self.generated_items = 0
        
    def generate_from_yaml(self, yaml_path: str, output_path: str) -> str:
        """Generate exact XML from YAML configuration with proper formatting"""
        print("🎯 Cholot Replicator V2 - Starting generation...")
        print("=" * 60)
        
        # Load YAML configuration
        with open(yaml_path, 'r', encoding='utf-8') as f:
            config = yaml.safe_load(f)
        
        # Create XML manually to avoid namespace issues
        xml_output = self._generate_xml_manually(config, output_path)
        
        print(f"✅ Generated XML: {output_path}")
        print(f"📊 Total items: {self.generated_items}")
        print(f"🎯 Target items: 65")
        
        return xml_output

    def _generate_xml_manually(self, config: Dict, output_path: str) -> str:
        """Generate XML manually with exact formatting"""
        
        # Start building XML as text for exact control
        xml_lines = []
        xml_lines.append('<?xml version="1.0" encoding="UTF-8" ?>')
        xml_lines.append('<!-- This is a WordPress eXtended RSS file generated by WordPress as an export of your site. -->')
        xml_lines.append('<!-- It contains information about your site\'s posts, pages, comments, categories, and other content. -->')
        xml_lines.append('<!-- You may use this file to transfer that content from one site to another. -->')
        xml_lines.append('<!-- This file is not intended to serve as a complete backup of your site. -->')
        xml_lines.append('')
        xml_lines.append('<!-- To import this information into a WordPress site follow these steps: -->')
        xml_lines.append('<!-- 1. Log in to that site as an administrator. -->')
        xml_lines.append('<!-- 2. Go to Tools: Import in the WordPress admin panel. -->')
        xml_lines.append('<!-- 3. Install the "WordPress" importer from the list. -->')
        xml_lines.append('<!-- 4. Activate & Run Importer. -->')
        xml_lines.append('<!-- 5. Upload this file using the form provided on that page. -->')
        xml_lines.append('<!-- 6. You will first be asked to map the authors in this export file to users -->')
        xml_lines.append('<!--    on the site. For each author, you may choose to map to an -->')
        xml_lines.append('<!--    existing user on the site or to create a new user. -->')
        xml_lines.append('<!-- 7. WordPress will then import each of the posts, pages, comments, categories, etc. -->')
        xml_lines.append('<!--    contained in this file into your site. -->')
        xml_lines.append('')
        xml_lines.append('\t<!-- generator="WordPress/5.2.2" created="2019-07-18 09:46" -->')
        xml_lines.append('<rss version="2.0"')
        xml_lines.append('\txmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"')
        xml_lines.append('\txmlns:content="http://purl.org/rss/1.0/modules/content/"')
        xml_lines.append('\txmlns:wfw="http://wellformedweb.org/CommentAPI/"')
        xml_lines.append('\txmlns:dc="http://purl.org/dc/elements/1.1/"')
        xml_lines.append('\txmlns:wp="http://wordpress.org/export/1.2/"')
        xml_lines.append('>')
        xml_lines.append('')
        xml_lines.append('<channel>')
        
        # Site info
        xml_lines.append('\t<title>Cholot</title>')
        xml_lines.append('\t<link>http://ridianur.com/wp/cholot</link>')
        xml_lines.append('\t<description>Just another WordPress site</description>')
        xml_lines.append('\t<pubDate>Thu, 18 Jul 2019 09:46:57 +0000</pubDate>')
        xml_lines.append('\t<language>en-US</language>')
        xml_lines.append('\t<wp:wxr_version>1.2</wp:wxr_version>')
        xml_lines.append('\t<wp:base_site_url>http://ridianur.com/wp/cholot</wp:base_site_url>')
        xml_lines.append('\t<wp:base_blog_url>http://ridianur.com/wp/cholot</wp:base_blog_url>')
        xml_lines.append('')
        
        # Author
        xml_lines.append('\t\t<wp:author><wp:author_id>1</wp:author_id><wp:author_login><![CDATA[admin]]></wp:author_login><wp:author_email><![CDATA[ridianur@yahoo.com]]></wp:author_email><wp:author_display_name><![CDATA[admin]]></wp:author_display_name><wp:author_first_name><![CDATA[]]></wp:author_first_name><wp:author_last_name><![CDATA[]]></wp:author_last_name></wp:author>')
        xml_lines.append('')
        
        # Categories
        xml_lines.append('\t\t<wp:category>')
        xml_lines.append('\t\t<wp:term_id>10</wp:term_id>')
        xml_lines.append('\t\t<wp:category_nicename><![CDATA[life]]></wp:category_nicename>')
        xml_lines.append('\t\t<wp:category_parent><![CDATA[]]></wp:category_parent>')
        xml_lines.append('\t\t<wp:cat_name><![CDATA[Life]]></wp:cat_name>')
        xml_lines.append('\t</wp:category>')
        xml_lines.append('\t\t<wp:category>')
        xml_lines.append('\t\t<wp:term_id>8</wp:term_id>')
        xml_lines.append('\t\t<wp:category_nicename><![CDATA[people]]></wp:category_nicename>')
        xml_lines.append('\t\t<wp:category_parent><![CDATA[]]></wp:category_parent>')
        xml_lines.append('\t\t<wp:cat_name><![CDATA[People]]></wp:cat_name>')
        xml_lines.append('\t</wp:category>')
        
        # Tags
        tags = [
            (17, 'humming'), (18, 'liquid'), (19, 'magic'), (20, 'movie'),
            (21, 'technology'), (22, 'travel'), (23, 'wildfire')
        ]
        
        for tag_id, tag_slug in tags:
            xml_lines.append('\t\t<wp:tag>')
            xml_lines.append(f'\t\t<wp:term_id>{tag_id}</wp:term_id>')
            xml_lines.append(f'\t\t<wp:tag_slug><![CDATA[{tag_slug}]]></wp:tag_slug>')
            xml_lines.append(f'\t\t<wp:tag_name><![CDATA[{tag_slug}]]></wp:tag_name>')
            xml_lines.append('\t</wp:tag>')
        
        # Nav menu term
        xml_lines.append('\t\t<wp:term>')
        xml_lines.append('\t\t<wp:term_id>16</wp:term_id>')
        xml_lines.append('\t\t<wp:term_taxonomy>nav_menu</wp:term_taxonomy>')
        xml_lines.append('\t\t<wp:term_slug><![CDATA[primary]]></wp:term_slug>')
        xml_lines.append('\t\t<wp:term_name><![CDATA[Primary Menu]]></wp:term_name>')
        xml_lines.append('\t</wp:term>')
        
        # Add all items in correct order
        self._add_items_manually(xml_lines, config)
        
        # Close XML
        xml_lines.append('</channel>')
        xml_lines.append('</rss>')
        
        # Write to file
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(xml_lines))
        
        return output_path
    
    def _add_items_manually(self, xml_lines: List[str], config: Dict):
        """Add all items manually in correct order"""
        
        # 1. Media attachments (27 items)
        media_items = config.get('media', [])
        for media in media_items:
            self._add_attachment_item(xml_lines, media)
            
        # 2. Custom Headers/Footers (3 items)
        custom_headers = config.get('custom_headers', [])
        for header in custom_headers:
            self._add_elementor_library_item(xml_lines, header, 'header')
            
        custom_footers = config.get('custom_footers', [])
        for footer in custom_footers:
            self._add_elementor_library_item(xml_lines, footer, 'footer')
            
        # 3. Contact Form (1 item)
        self._add_contact_form_item(xml_lines, config.get('contact_forms', [{}])[0] if config.get('contact_forms') else {'id': 5})
        
        # 4. Pages (8 items)
        pages = config.get('pages', [])
        for page in pages:
            self._add_page_item(xml_lines, page)
            
        # 5. Posts (8 items)
        posts = config.get('posts', [])
        for post in posts:
            self._add_post_item(xml_lines, post)
            
        # 6. Menu Items (11 items)
        menus = config.get('menus', [])
        if menus:
            menu_items = menus[0].get('items', [])
            for menu_item in menu_items:
                self._add_menu_item(xml_lines, menu_item)
                
        # 7. Elementor Templates (7 items)
        templates = config.get('elementor_templates', [])
        for template in templates:
            self._add_elementor_library_item(xml_lines, template, 'page')
    
    def _add_attachment_item(self, xml_lines: List[str], media: Dict):
        """Add attachment item"""
        media_id = media.get('id')
        title = media.get('title', f"Attachment {media_id}")
        filename = media.get('filename', f"file-{media_id}")
        
        xml_lines.append('')
        xml_lines.append('\t<item>')
        xml_lines.append(f'\t\t<title><![CDATA[{title}]]></title>')
        xml_lines.append(f'\t\t<link>http://ridianur.com/wp/cholot/{filename}/</link>')
        xml_lines.append('\t\t<pubDate>Thu, 04 Jul 2019 10:16:07 +0000</pubDate>')
        xml_lines.append('\t\t<dc:creator><![CDATA[admin]]></dc:creator>')
        xml_lines.append(f'\t\t<guid isPermaLink="false">http://ridianur.com/wp/cholot/{filename}/</guid>')
        xml_lines.append('\t\t<description></description>')
        xml_lines.append('\t\t<content:encoded><![CDATA[]]></content:encoded>')
        xml_lines.append('\t\t<excerpt:encoded><![CDATA[]]></excerpt:encoded>')
        xml_lines.append(f'\t\t<wp:post_id>{media_id}</wp:post_id>')
        xml_lines.append('\t\t<wp:post_date><![CDATA[2019-07-04 10:16:07]]></wp:post_date>')
        xml_lines.append('\t\t<wp:post_date_gmt><![CDATA[2019-07-04 10:16:07]]></wp:post_date_gmt>')
        xml_lines.append('\t\t<wp:comment_status><![CDATA[open]]></wp:comment_status>')
        xml_lines.append('\t\t<wp:ping_status><![CDATA[closed]]></wp:ping_status>')
        xml_lines.append(f'\t\t<wp:post_name><![CDATA[{filename}]]></wp:post_name>')
        xml_lines.append('\t\t<wp:status><![CDATA[inherit]]></wp:status>')
        xml_lines.append('\t\t<wp:post_parent>0</wp:post_parent>')
        xml_lines.append('\t\t<wp:menu_order>0</wp:menu_order>')
        xml_lines.append('\t\t<wp:post_type><![CDATA[attachment]]></wp:post_type>')
        xml_lines.append('\t\t<wp:post_password><![CDATA[]]></wp:post_password>')
        xml_lines.append('\t\t<wp:is_sticky>0</wp:is_sticky>')
        xml_lines.append(f'\t\t<wp:attachment_url><![CDATA[http://ridianur.com/wp/cholot/wp-content/uploads/2019/07/{filename}.jpg]]></wp:attachment_url>')
        xml_lines.append('\t\t<wp:postmeta>')
        xml_lines.append('\t\t\t<wp:meta_key><![CDATA[_wp_attached_file]]></wp:meta_key>')
        xml_lines.append(f'\t\t\t<wp:meta_value><![CDATA[2019/07/{filename}.jpg]]></wp:meta_value>')
        xml_lines.append('\t\t</wp:postmeta>')
        xml_lines.append('\t</item>')
        
        self.generated_items += 1
    
    def _add_elementor_library_item(self, xml_lines: List[str], item: Dict, template_type: str):
        """Add Elementor library item (header, footer, page template)"""
        item_id = item.get('id')
        title = item.get('title', f"Template {item_id}")
        
        xml_lines.append('')
        xml_lines.append('\t<item>')
        xml_lines.append(f'\t\t<title><![CDATA[{title}]]></title>')
        xml_lines.append(f'\t\t<link>http://ridianur.com/wp/cholot/?post_type=elementor_library&amp;p={item_id}</link>')
        xml_lines.append('\t\t<pubDate>Thu, 04 Jul 2019 10:16:07 +0000</pubDate>')
        xml_lines.append('\t\t<dc:creator><![CDATA[admin]]></dc:creator>')
        xml_lines.append(f'\t\t<guid isPermaLink="false">http://ridianur.com/wp/cholot/?post_type=elementor_library&amp;p={item_id}</guid>')
        xml_lines.append('\t\t<description></description>')
        xml_lines.append('\t\t<content:encoded><![CDATA[]]></content:encoded>')
        xml_lines.append('\t\t<excerpt:encoded><![CDATA[]]></excerpt:encoded>')
        xml_lines.append(f'\t\t<wp:post_id>{item_id}</wp:post_id>')
        xml_lines.append('\t\t<wp:post_date><![CDATA[2019-07-04 10:16:07]]></wp:post_date>')
        xml_lines.append('\t\t<wp:post_date_gmt><![CDATA[2019-07-04 10:16:07]]></wp:post_date_gmt>')
        xml_lines.append('\t\t<wp:comment_status><![CDATA[closed]]></wp:comment_status>')
        xml_lines.append('\t\t<wp:ping_status><![CDATA[closed]]></wp:ping_status>')
        xml_lines.append(f'\t\t<wp:post_name><![CDATA[{template_type}-{item_id}]]></wp:post_name>')
        xml_lines.append('\t\t<wp:status><![CDATA[publish]]></wp:status>')
        xml_lines.append('\t\t<wp:post_parent>0</wp:post_parent>')
        xml_lines.append('\t\t<wp:menu_order>0</wp:menu_order>')
        xml_lines.append('\t\t<wp:post_type><![CDATA[elementor_library]]></wp:post_type>')
        xml_lines.append('\t\t<wp:post_password><![CDATA[]]></wp:post_password>')
        xml_lines.append('\t\t<wp:is_sticky>0</wp:is_sticky>')
        xml_lines.append('\t\t<wp:postmeta>')
        xml_lines.append('\t\t\t<wp:meta_key><![CDATA[_elementor_template_type]]></wp:meta_key>')
        xml_lines.append(f'\t\t\t<wp:meta_value><![CDATA[{template_type}]]></wp:meta_value>')
        xml_lines.append('\t\t</wp:postmeta>')
        xml_lines.append('\t</item>')
        
        self.generated_items += 1
    
    def _add_contact_form_item(self, xml_lines: List[str], form: Dict):
        """Add contact form item"""
        form_id = form.get('id', 5)
        
        xml_lines.append('')
        xml_lines.append('\t<item>')
        xml_lines.append('\t\t<title><![CDATA[Contact form]]></title>')
        xml_lines.append(f'\t\t<link>http://ridianur.com/wp/cholot/?post_type=wpcf7_contact_form&amp;p={form_id}</link>')
        xml_lines.append('\t\t<pubDate>Thu, 04 Jul 2019 10:16:07 +0000</pubDate>')
        xml_lines.append('\t\t<dc:creator><![CDATA[admin]]></dc:creator>')
        xml_lines.append(f'\t\t<guid isPermaLink="false">http://ridianur.com/wp/cholot/?post_type=wpcf7_contact_form&amp;p={form_id}</guid>')
        xml_lines.append('\t\t<description></description>')
        xml_lines.append('\t\t<content:encoded><![CDATA[]]></content:encoded>')
        xml_lines.append('\t\t<excerpt:encoded><![CDATA[]]></excerpt:encoded>')
        xml_lines.append(f'\t\t<wp:post_id>{form_id}</wp:post_id>')
        xml_lines.append('\t\t<wp:post_date><![CDATA[2019-07-04 10:16:07]]></wp:post_date>')
        xml_lines.append('\t\t<wp:post_date_gmt><![CDATA[2019-07-04 10:16:07]]></wp:post_date_gmt>')
        xml_lines.append('\t\t<wp:comment_status><![CDATA[closed]]></wp:comment_status>')
        xml_lines.append('\t\t<wp:ping_status><![CDATA[closed]]></wp:ping_status>')
        xml_lines.append('\t\t<wp:post_name><![CDATA[contact-form-1]]></wp:post_name>')
        xml_lines.append('\t\t<wp:status><![CDATA[publish]]></wp:status>')
        xml_lines.append('\t\t<wp:post_parent>0</wp:post_parent>')
        xml_lines.append('\t\t<wp:menu_order>0</wp:menu_order>')
        xml_lines.append('\t\t<wp:post_type><![CDATA[wpcf7_contact_form]]></wp:post_type>')
        xml_lines.append('\t\t<wp:post_password><![CDATA[]]></wp:post_password>')
        xml_lines.append('\t\t<wp:is_sticky>0</wp:is_sticky>')
        xml_lines.append('\t</item>')
        
        self.generated_items += 1
    
    def _add_page_item(self, xml_lines: List[str], page: Dict):
        """Add page item"""
        page_id = page.get('id')
        title = page.get('title', f"Page {page_id}")
        slug = page.get('slug', f"page-{page_id}")
        
        # Handle homepage (empty slug)
        if slug == "":
            link_url = "http://ridianur.com/wp/cholot/"
            post_name = ""
        else:
            link_url = f"http://ridianur.com/wp/cholot/{slug}/"
            post_name = slug
            
        xml_lines.append('')
        xml_lines.append('\t<item>')
        xml_lines.append(f'\t\t<title><![CDATA[{title}]]></title>')
        xml_lines.append(f'\t\t<link>{link_url}</link>')
        xml_lines.append('\t\t<pubDate>Thu, 04 Jul 2019 10:16:07 +0000</pubDate>')
        xml_lines.append('\t\t<dc:creator><![CDATA[admin]]></dc:creator>')
        xml_lines.append(f'\t\t<guid isPermaLink="false">http://ridianur.com/wp/cholot/?page_id={page_id}</guid>')
        xml_lines.append('\t\t<description></description>')
        xml_lines.append('\t\t<content:encoded><![CDATA[]]></content:encoded>')
        xml_lines.append('\t\t<excerpt:encoded><![CDATA[]]></excerpt:encoded>')
        xml_lines.append(f'\t\t<wp:post_id>{page_id}</wp:post_id>')
        xml_lines.append('\t\t<wp:post_date><![CDATA[2019-07-04 10:16:07]]></wp:post_date>')
        xml_lines.append('\t\t<wp:post_date_gmt><![CDATA[2019-07-04 10:16:07]]></wp:post_date_gmt>')
        xml_lines.append('\t\t<wp:comment_status><![CDATA[closed]]></wp:comment_status>')
        xml_lines.append('\t\t<wp:ping_status><![CDATA[closed]]></wp:ping_status>')
        xml_lines.append(f'\t\t<wp:post_name><![CDATA[{post_name}]]></wp:post_name>')
        xml_lines.append(f'\t\t<wp:status><![CDATA[{page.get("status", "publish")}]]></wp:status>')
        xml_lines.append(f'\t\t<wp:post_parent>{page.get("parent", 0)}</wp:post_parent>')
        xml_lines.append(f'\t\t<wp:menu_order>{page.get("menu_order", 0)}</wp:menu_order>')
        xml_lines.append('\t\t<wp:post_type><![CDATA[page]]></wp:post_type>')
        xml_lines.append('\t\t<wp:post_password><![CDATA[]]></wp:post_password>')
        xml_lines.append('\t\t<wp:is_sticky>0</wp:is_sticky>')
        
        # Add Cholot meta
        cholot_meta = page.get('cholot_meta', {})
        for meta_key, meta_value in cholot_meta.items():
            xml_lines.append('\t\t<wp:postmeta>')
            xml_lines.append(f'\t\t\t<wp:meta_key><![CDATA[{meta_key}]]></wp:meta_key>')
            xml_lines.append(f'\t\t\t<wp:meta_value><![CDATA[{meta_value}]]></wp:meta_value>')
            xml_lines.append('\t\t</wp:postmeta>')
        
        xml_lines.append('\t</item>')
        
        self.generated_items += 1
    
    def _add_post_item(self, xml_lines: List[str], post: Dict):
        """Add post item"""
        post_id = post.get('id')
        title = post.get('title', f"Post {post_id}")
        slug = post.get('slug', f"post-{post_id}")
        post_date = post.get('date', '2019-07-04 11:13:19')
        
        xml_lines.append('')
        xml_lines.append('\t<item>')
        xml_lines.append(f'\t\t<title><![CDATA[{title}]]></title>')
        xml_lines.append(f'\t\t<link>http://ridianur.com/wp/cholot/{slug}/</link>')
        xml_lines.append(f'\t\t<pubDate>{post_date.replace(" ", " ")} +0000</pubDate>')
        xml_lines.append('\t\t<dc:creator><![CDATA[admin]]></dc:creator>')
        xml_lines.append(f'\t\t<guid isPermaLink="false">http://ridianur.com/wp/cholot/?p={post_id}</guid>')
        xml_lines.append('\t\t<description></description>')
        xml_lines.append('\t\t<content:encoded><![CDATA[Sample post content.]]></content:encoded>')
        xml_lines.append('\t\t<excerpt:encoded><![CDATA[]]></excerpt:encoded>')
        
        # Categories
        categories = post.get('categories', [])
        for cat in categories:
            xml_lines.append(f'\t\t<category domain="category" nicename="{cat.lower()}"><![CDATA[{cat}]]></category>')
        
        # Tags
        tags = post.get('tags', [])
        for tag in tags:
            xml_lines.append(f'\t\t<category domain="post_tag" nicename="{tag}"><![CDATA[{tag}]]></category>')
            
        xml_lines.append(f'\t\t<wp:post_id>{post_id}</wp:post_id>')
        xml_lines.append(f'\t\t<wp:post_date><![CDATA[{post_date}]]></wp:post_date>')
        xml_lines.append(f'\t\t<wp:post_date_gmt><![CDATA[{post_date}]]></wp:post_date_gmt>')
        xml_lines.append('\t\t<wp:comment_status><![CDATA[open]]></wp:comment_status>')
        xml_lines.append('\t\t<wp:ping_status><![CDATA[open]]></wp:ping_status>')
        xml_lines.append(f'\t\t<wp:post_name><![CDATA[{slug}]]></wp:post_name>')
        xml_lines.append(f'\t\t<wp:status><![CDATA[{post.get("status", "publish")}]]></wp:status>')
        xml_lines.append('\t\t<wp:post_parent>0</wp:post_parent>')
        xml_lines.append('\t\t<wp:menu_order>0</wp:menu_order>')
        xml_lines.append('\t\t<wp:post_type><![CDATA[post]]></wp:post_type>')
        xml_lines.append('\t\t<wp:post_password><![CDATA[]]></wp:post_password>')
        xml_lines.append('\t\t<wp:is_sticky>0</wp:is_sticky>')
        xml_lines.append('\t</item>')
        
        self.generated_items += 1
    
    def _add_menu_item(self, xml_lines: List[str], menu_item: Dict):
        """Add menu item"""
        item_id = menu_item.get('id')
        title = menu_item.get('title', '')
        
        xml_lines.append('')
        xml_lines.append('\t<item>')
        xml_lines.append(f'\t\t<title><![CDATA[{title}]]></title>')
        xml_lines.append(f'\t\t<link>http://ridianur.com/wp/cholot/?p={item_id}</link>')
        xml_lines.append('\t\t<pubDate>Thu, 04 Jul 2019 10:16:07 +0000</pubDate>')
        xml_lines.append('\t\t<dc:creator><![CDATA[admin]]></dc:creator>')
        xml_lines.append(f'\t\t<guid isPermaLink="false">http://ridianur.com/wp/cholot/?p={item_id}</guid>')
        xml_lines.append('\t\t<description></description>')
        xml_lines.append('\t\t<content:encoded><![CDATA[ ]]></content:encoded>')
        xml_lines.append('\t\t<excerpt:encoded><![CDATA[]]></excerpt:encoded>')
        
        # Menu category
        xml_lines.append('\t\t<category domain="nav_menu" nicename="primary"><![CDATA[Primary Menu]]></category>')
        
        xml_lines.append(f'\t\t<wp:post_id>{item_id}</wp:post_id>')
        xml_lines.append('\t\t<wp:post_date><![CDATA[2019-07-04 10:16:07]]></wp:post_date>')
        xml_lines.append('\t\t<wp:post_date_gmt><![CDATA[2019-07-04 10:16:07]]></wp:post_date_gmt>')
        xml_lines.append('\t\t<wp:comment_status><![CDATA[closed]]></wp:comment_status>')
        xml_lines.append('\t\t<wp:ping_status><![CDATA[closed]]></wp:ping_status>')
        xml_lines.append(f'\t\t<wp:post_name><![CDATA[{item_id}]]></wp:post_name>')
        xml_lines.append('\t\t<wp:status><![CDATA[publish]]></wp:status>')
        xml_lines.append('\t\t<wp:post_parent>0</wp:post_parent>')
        xml_lines.append(f'\t\t<wp:menu_order>{menu_item.get("menu_order", 1)}</wp:menu_order>')
        xml_lines.append('\t\t<wp:post_type><![CDATA[nav_menu_item]]></wp:post_type>')
        xml_lines.append('\t\t<wp:post_password><![CDATA[]]></wp:post_password>')
        xml_lines.append('\t\t<wp:is_sticky>0</wp:is_sticky>')
        
        # Menu meta
        meta_items = [
            ('_menu_item_type', menu_item.get('type', 'post_type')),
            ('_menu_item_menu_item_parent', str(menu_item.get('parent', 0))),
            ('_menu_item_object', 'page'),
            ('_menu_item_object_id', str(menu_item.get('object_id', item_id))),
            ('_menu_item_target', ''),
            ('_menu_item_classes', ''),
            ('_menu_item_xfn', ''),
            ('_menu_item_url', menu_item.get('url', ''))
        ]
        
        for meta_key, meta_value in meta_items:
            xml_lines.append('\t\t<wp:postmeta>')
            xml_lines.append(f'\t\t\t<wp:meta_key><![CDATA[{meta_key}]]></wp:meta_key>')
            xml_lines.append(f'\t\t\t<wp:meta_value><![CDATA[{meta_value}]]></wp:meta_value>')
            xml_lines.append('\t\t</wp:postmeta>')
        
        xml_lines.append('\t</item>')
        
        self.generated_items += 1


def main():
    import sys
    
    if len(sys.argv) < 3:
        print("Usage: python cholot_replicator_v2.py <yaml_file> <output_xml>")
        sys.exit(1)
    
    yaml_file = sys.argv[1]
    output_xml = sys.argv[2]
    
    replicator = CholtReplicatorV2()
    replicator.generate_from_yaml(yaml_file, output_xml)


if __name__ == "__main__":
    main()