<?php
/**
 * Generiert WordPress XML Export aus Elementor JSON Struktur
 * Basierend auf der Analyse von Gemini und unseren generierten Daten
 */

echo "📦 ELEMENTOR TO XML EXPORTER\n";
echo "============================\n\n";

// Lade die generierte Struktur
$json_file = 'generated_cholot_structure.json';
if (!file_exists($json_file)) {
    die("❌ generated_cholot_structure.json nicht gefunden! Bitte erst exact_cholot_processor.php ausführen.\n");
}

$elementor_data = file_get_contents($json_file);
$elementor_array = json_decode($elementor_data, true);

echo "✅ Elementor Struktur geladen\n";
echo "   → " . count($elementor_array) . " Hauptsektionen gefunden\n";

// Zähle Widgets
$widget_count = substr_count($elementor_data, '"widgetType"');
$texticon_count = substr_count($elementor_data, '"widgetType":"cholot-texticon"');
$shape_count = substr_count($elementor_data, '"shape_divider_bottom":"curve"');

echo "   → $widget_count Widgets total\n";
echo "   → $texticon_count cholot-texticon Widgets\n";
echo "   → $shape_count Shape Dividers\n\n";

// XML Struktur erstellen
$xml_content = '<?xml version="1.0" encoding="UTF-8" ?>
<!-- WordPress XML Export Generator for Elementor Pages -->
<!-- Generated by RIMAN Processor based on Cholot Theme -->

<rss version="2.0"
    xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
    xmlns:content="http://purl.org/rss/1.0/modules/content/"
    xmlns:wfw="http://wellformedweb.org/CommentAPI/"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:wp="http://wordpress.org/export/1.2/"
>

<channel>
    <title>RIMAN GmbH - Umweltsanierung</title>
    <link>http://localhost:8081</link>
    <description>Professionelle Schadstoffsanierung</description>
    <pubDate>' . date('D, d M Y H:i:s +0000') . '</pubDate>
    <language>de-DE</language>
    <wp:wxr_version>1.2</wp:wxr_version>
    <wp:base_site_url>http://localhost:8081</wp:base_site_url>
    <wp:base_blog_url>http://localhost:8081</wp:base_blog_url>

    <wp:author>
        <wp:author_id>1</wp:author_id>
        <wp:author_login><![CDATA[admin]]></wp:author_login>
        <wp:author_email><![CDATA[admin@riman-gmbh.de]]></wp:author_email>
        <wp:author_display_name><![CDATA[Admin]]></wp:author_display_name>
        <wp:author_first_name><![CDATA[]]></wp:author_first_name>
        <wp:author_last_name><![CDATA[]]></wp:author_last_name>
    </wp:author>

    <generator>https://wordpress.org/?v=6.8</generator>

    <!-- RIMAN Homepage mit Cholot Design -->
    <item>
        <title>RIMAN Startseite</title>
        <link>http://localhost:8081/?page_id=3000</link>
        <pubDate>' . date('D, d M Y H:i:s +0000') . '</pubDate>
        <dc:creator><![CDATA[admin]]></dc:creator>
        <guid isPermaLink="false">http://localhost:8081/?page_id=3000</guid>
        <description></description>
        <content:encoded><![CDATA[]]></content:encoded>
        <excerpt:encoded><![CDATA[]]></excerpt:encoded>
        <wp:post_id>3000</wp:post_id>
        <wp:post_date><![CDATA[' . date('Y-m-d H:i:s') . ']]></wp:post_date>
        <wp:post_date_gmt><![CDATA[' . date('Y-m-d H:i:s') . ']]></wp:post_date_gmt>
        <wp:post_modified><![CDATA[' . date('Y-m-d H:i:s') . ']]></wp:post_modified>
        <wp:post_modified_gmt><![CDATA[' . date('Y-m-d H:i:s') . ']]></wp:post_modified_gmt>
        <wp:comment_status><![CDATA[closed]]></wp:comment_status>
        <wp:ping_status><![CDATA[closed]]></wp:ping_status>
        <wp:post_name><![CDATA[riman-startseite]]></wp:post_name>
        <wp:status><![CDATA[publish]]></wp:status>
        <wp:post_parent>0</wp:post_parent>
        <wp:menu_order>0</wp:menu_order>
        <wp:post_type><![CDATA[page]]></wp:post_type>
        <wp:post_password><![CDATA[]]></wp:post_password>
        <wp:is_sticky>0</wp:is_sticky>
        
        <!-- Elementor Version -->
        <wp:postmeta>
            <wp:meta_key><![CDATA[_elementor_version]]></wp:meta_key>
            <wp:meta_value><![CDATA[3.18.3]]></wp:meta_value>
        </wp:postmeta>
        
        <!-- Elementor Edit Mode -->
        <wp:postmeta>
            <wp:meta_key><![CDATA[_elementor_edit_mode]]></wp:meta_key>
            <wp:meta_value><![CDATA[builder]]></wp:meta_value>
        </wp:postmeta>
        
        <!-- Elementor Template Type -->
        <wp:postmeta>
            <wp:meta_key><![CDATA[_elementor_template_type]]></wp:meta_key>
            <wp:meta_value><![CDATA[wp-page]]></wp:meta_value>
        </wp:postmeta>
        
        <!-- Page Template -->
        <wp:postmeta>
            <wp:meta_key><![CDATA[_wp_page_template]]></wp:meta_key>
            <wp:meta_value><![CDATA[elementor_header_footer]]></wp:meta_value>
        </wp:postmeta>
        
        <!-- Elementor Data (Die Hauptdaten) -->
        <wp:postmeta>
            <wp:meta_key><![CDATA[_elementor_data]]></wp:meta_key>
            <wp:meta_value><![CDATA[' . htmlspecialchars($elementor_data, ENT_XML1, 'UTF-8') . ']]></wp:meta_value>
        </wp:postmeta>
        
        <!-- Elementor Controls Usage -->
        <wp:postmeta>
            <wp:meta_key><![CDATA[_elementor_controls_usage]]></wp:meta_key>
            <wp:meta_value><![CDATA[' . htmlspecialchars(json_encode([
                "column" => ["count" => 10],
                "section" => ["count" => 8],
                "image" => ["count" => 4],
                "cholot-texticon" => ["count" => $texticon_count],
                "text-editor" => ["count" => 2],
                "divider" => ["count" => 2]
            ]), ENT_XML1, 'UTF-8') . ']]></wp:meta_value>
        </wp:postmeta>
    </item>
    
    <!-- Service Pages für jede Dienstleistung -->
    <item>
        <title>Asbestsanierung</title>
        <link>http://localhost:8081/?page_id=3001</link>
        <pubDate>' . date('D, d M Y H:i:s +0000') . '</pubDate>
        <dc:creator><![CDATA[admin]]></dc:creator>
        <guid isPermaLink="false">http://localhost:8081/?page_id=3001</guid>
        <content:encoded><![CDATA[Professionelle Asbestsanierung nach TRGS 519]]></content:encoded>
        <wp:post_id>3001</wp:post_id>
        <wp:post_date><![CDATA[' . date('Y-m-d H:i:s') . ']]></wp:post_date>
        <wp:post_type><![CDATA[page]]></wp:post_type>
        <wp:status><![CDATA[publish]]></wp:status>
        <wp:post_parent>0</wp:post_parent>
        <wp:post_name><![CDATA[asbestsanierung]]></wp:post_name>
    </item>
    
    <item>
        <title>PCB-Sanierung</title>
        <link>http://localhost:8081/?page_id=3002</link>
        <pubDate>' . date('D, d M Y H:i:s +0000') . '</pubDate>
        <dc:creator><![CDATA[admin]]></dc:creator>
        <guid isPermaLink="false">http://localhost:8081/?page_id=3002</guid>
        <content:encoded><![CDATA[Fachgerechte PCB-Sanierung]]></content:encoded>
        <wp:post_id>3002</wp:post_id>
        <wp:post_date><![CDATA[' . date('Y-m-d H:i:s') . ']]></wp:post_date>
        <wp:post_type><![CDATA[page]]></wp:post_type>
        <wp:status><![CDATA[publish]]></wp:status>
        <wp:post_parent>0</wp:post_parent>
        <wp:post_name><![CDATA[pcb-sanierung]]></wp:post_name>
    </item>
    
    <item>
        <title>Schimmelsanierung</title>
        <link>http://localhost:8081/?page_id=3003</link>
        <pubDate>' . date('D, d M Y H:i:s +0000') . '</pubDate>
        <dc:creator><![CDATA[admin]]></dc:creator>
        <guid isPermaLink="false">http://localhost:8081/?page_id=3003</guid>
        <content:encoded><![CDATA[Nachhaltige Schimmelsanierung]]></content:encoded>
        <wp:post_id>3003</wp:post_id>
        <wp:post_date><![CDATA[' . date('Y-m-d H:i:s') . ']]></wp:post_date>
        <wp:post_type><![CDATA[page]]></wp:post_type>
        <wp:status><![CDATA[publish]]></wp:status>
        <wp:post_parent>0</wp:post_parent>
        <wp:post_name><![CDATA[schimmelsanierung]]></wp:post_name>
    </item>

</channel>
</rss>';

// Speichere XML
$xml_filename = 'riman-elementor-export.xml';
file_put_contents($xml_filename, $xml_content);

echo "💾 XML Export gespeichert als: $xml_filename\n";
echo "   → Größe: " . number_format(filesize($xml_filename) / 1024, 2) . " KB\n\n";

echo "📋 IMPORT ANLEITUNG:\n";
echo "===================\n";
echo "1. WordPress Admin öffnen: http://localhost:8081/wp-admin\n";
echo "2. Gehe zu: Werkzeuge → Daten importieren\n";
echo "3. Wähle 'WordPress' (installiere Importer falls nötig)\n";
echo "4. Lade die Datei '$xml_filename' hoch\n";
echo "5. Weise Autoren zu (wähle 'admin')\n";
echo "6. Importiere Medien NICHT aktivieren\n";
echo "7. Import starten\n\n";

echo "🎯 NACH DEM IMPORT:\n";
echo "==================\n";
echo "1. Öffne die Seite: http://localhost:8081/?page_id=3000\n";
echo "2. Falls Widgets nicht angezeigt werden:\n";
echo "   → Seite im Elementor Editor öffnen\n";
echo "   → Einmal speichern (triggert Widget-Registrierung)\n";
echo "3. Cache leeren (Strg+F5)\n\n";

echo "✅ XML Export erfolgreich erstellt!\n";