site:
  title: "RIMAN GmbH - Professionelle Schadstoffsanierung"
  url: "https://riman-gmbh.de"

pages:
  - title: "Startseite"
    slug: "home"
    template: "elementor_header_footer"
    elementor_data_file: "riman-homepage.json"
